config/routes.rb
# frozen_string_literal: true

RedmineApp::Application.routes.draw do
  concern :active_scaffold, ActiveScaffold::Routing::Basic.new(association: true)
  resources(:telegram_chats, concerns: :active_scaffold)
  get '/users/:id/email_extra_preferences', to: 'email_extra_preferences#index',
                                            as: 'email_extra_preferences'
  put '/users/:id/email_extra_preferences', to: 'email_extra_preferences#update'
  get '/users/:id/telegram_preferences', to: 'telegram_preferences#index',
                                         as: 'telegram_preferences'
  put '/users/:id/telegram_preferences', to: 'telegram_preferences#update'
end

app/controllers/telegram_preferences_controller.rb
# frozen_string_literal: true

class TelegramPreferencesController < ApplicationController
  include ::Notifyme::UserPreferencesControllerConcern

  before_action :build_chats

  helper :users

  private

  def build_chats
    @chats = TelegramChat.where(user: @user)
  end

  def pref_params
    r = params[model_class.model_name.param_key]
          .permit(:no_self_notified, :issues, :git, issues_project_ids: [], git_project_ids: [])
    r[:issues_project_ids] ||= []
    r[:git_project_ids] ||= []
    r
  end
end

app/views/telegram_preferences/_filter_input.html.erb
<%
hidden_id = "#{field}-notified-projects"
hidden_js = "if (this.value == \"selected\") {$(\"\##{hidden_id}\").show();} else {$(\"\##{hidden_id}\").hide();}"
projects_key = "#{::UserTelegramPreferences.model_name.param_key}[#{field}_project_ids][]"
%>
<p>
  <%= label_tag "user_mail_notification", l(:description_user_mail_notification), :class => "hidden-for-sighted" %>
  <label><%= t("field_#{field}") %></label>
  <%= f.select(field, @pref.send("#{field}_options"), { no_label: true }, {onchange: hidden_js }) %>
</p>
<%= content_tag 'div', :id => hidden_id, :style => (@pref.send(field) == 'selected' ? '' : 'display:none;') do %>
  <%= render_project_nested_lists(@user.projects) do |project|
    content_tag('label',
      check_box_tag(
        projects_key, project.id,
        @pref.send("#{field}_project_ids").include?(project.id),
        :id => nil
        ) + ' ' + h(project.name)
    )
    end %>
  <%= hidden_field_tag projects_key, '' %>
  <p><em class="info"><%= l(:text_user_mail_option) %></em></p>
<% end %>

app/views/telegram_preferences/_telegram_chats.html.erb
<h3>Configuração</h3>
<p>Para vincular um chat Telegram à sua conta neste Redmine envie a seguinte
  mensagem para <span style="font-weight: bold">
    <%= Notifyme::Settings.telegram_bot_name %></span>:</p>
<div class="box" >
  <pre>/user_set <%= User.current.api_key %></pre>
</div>
<p>Para desvincular um chat Telegram de sua conta neste Redmine envie a seguinte
  mensagem para <span style="font-weight: bold">
    <%= Notifyme::Settings.telegram_bot_name %></span>:</p>
<div class="box">
  <pre>/user_unset</pre>
</div>
<h3>Chats vinculados</h3>
<% if @chats.empty? %>
  <p><em>Nenhum chat Telegram vinculado</em></p>
<% else %>
  <ul>
    <% @chats.each do |c| %>
      <li><%= c %></li>
    <% end %>
  </ul>
<% end %>

app/views/telegram_preferences/_telegram_settings.html.erb
<%= labelled_form_for @pref, url: telegram_preferences_path(@pref.user), method: :put do |f| %>
  <fieldset class="box">
    <legend><%= l(:label_user_telegram_settings)%></legend>
    <%= error_messages_for @pref %>
    <% %w(issues git).each do |field| %>
      <%= render partial: 'filter_input', locals: {f: f, field: field} %>
    <% end %>
    <p>
      <%= f.check_box :no_self_notified, label: l(:label_user_mail_no_self_notified) %>
    </p>
    <%= submit_tag l(:button_update) %>
  </fieldset>
<% end %>

app/views/telegram_preferences/index.html.erb
<h2><%= t(:label_telegram_preferences) %>: <%= @pref.user %></h2>
<%= render partial: 'telegram_settings' %>
<%= render partial: 'telegram_chats' %>