config/routes.rb
# frozen_string_literal: true

RedmineApp::Application.routes.draw do
  concern :active_scaffold, ActiveScaffold::Routing::Basic.new(association: true)
  resources(:telegram_chats, concerns: :active_scaffold)
  get '/users/:id/email_extra_preferences', to: 'email_extra_preferences#index',
                                            as: 'email_extra_preferences'
  put '/users/:id/email_extra_preferences', to: 'email_extra_preferences#update'
  get '/users/:id/telegram_preferences', to: 'telegram_preferences#index',
                                         as: 'telegram_preferences'
  put '/users/:id/telegram_preferences', to: 'telegram_preferences#update'
end

app/controllers/email_extra_preferences_controller.rb
# frozen_string_literal: true

class EmailExtraPreferencesController < ApplicationController
  include ::Notifyme::UserPreferencesControllerConcern

  private

  def pref_params
    r = params[model_class.model_name.param_key].permit(:assignee_reminder)
    r[:assignee_reminder] = sanitize_boolean(r[:assignee_reminder])
    r
  end

  def sanitize_boolean(value) # rubocop:disable Naming/PredicateMethod
    return false if value.blank?
    return false if %w[0 false].include?(value.to_s.strip)

    true
  end
end

app/views/email_extra_preferences/index.html.erb
<h2><%= t(:label_email_extra_preferences) %>: <%= @pref.user %></h2>
<%= labelled_form_for @pref, url: email_extra_preferences_path(@pref.user), method: :put do |f| %>
  <fieldset class="box">
    <%= error_messages_for @pref %>
    <p>
      <%= f.check_box :assignee_reminder, label: l(:label_user_mail_assignee_reminder) %>
    </p>
    <%= submit_tag l(:button_update) %>
  </fieldset>
<% end %>